styling fixes
tronprotocol/wallet-web pull request #153
Opened 2018-05-05 09:26 UTC by lazarovicedo

keep footer on the bottom, added loading bar (vertical centered) on token list, truncate urls on representatives list, display wallet version on the footer (from data stored on package.json), truncate token name on send page

2018-05-05 15:34 UTC, DevObs1 reviewed
Hi @lazarovicedo,
The sitekey corresponds to the domain tronscan.org?
src/components/account/LoginWithCaptcha.js, line 108

2018-05-05 15:41 UTC, lazarovicedo commented
DevObs1, no. that sitekey is for localhost. Anyway, that captcha feature will be disabled by now as suggested by @Rovak

2018-05-05 15:43 UTC, DevObs1 commented
Why should it be disabled?
Because I wanted to work on this fix too :) but I was thinking of contacting @Rovak Rovak before to generate a sitekey for PR

2018-05-05 16:44 UTC, lazarovicedo commented
@DevObs1 , Do you know any popular web wallet that implements a captcha?

2018-05-05 19:18 UTC, DevObs1 commented
@lazarovicedo : I looked in a dozen sites but none offers reCaptcha (either for login or registration)

2018-05-11 17:44 UTC, Rovak reviewed
I get this error when registering a new account

![screenshot from 2018-05-11 19-45-26](https://user-images.githubusercontent.com/376155/39938637-e3d46540-5553-11e8-91a5-3e9356608bbc.png)

2018-05-11 17:47 UTC, Rovak commented
After registering / logging in and refreshing i get this error 

![screenshot from 2018-05-11 19-46-17](https://user-images.githubusercontent.com/376155/39938703-17dec736-5554-11e8-9c1a-6763d0d663fb.png)

2018-05-11 17:49 UTC, Rovak requested changes

2018-05-11 17:49 UTC, Rovak commented on src/reducers/app.js
> +  activeLanguage: (Lockr.get("language") !== undefined ? Lockr.get("language") : 'en'),
`Locker.get` has a second parameter for a default value, this can be simplified  to `Lockr.get("language", "en")`

2018-05-11 17:49 UTC, Rovak commented on src/reducers/app.js
> +    key: (Lockr.get("account_key") !== undefined ? Lockr.get("account_key") : undefined),
can be simplified to `Lockr.get("account_key")`

2018-05-11 17:49 UTC, Rovak commented on src/reducers/app.js
> +    isLoggedIn: (Lockr.get("account_key") !== undefined ? true : false)
can be simplified to `Lockr.get("account_key") !== undefined`

2018-05-11 18:16 UTC, lazarovicedo reviewed
simplified to Lockr.get("account_key")

2018-05-13 20:13 UTC, merged

2018-05-13 20:13 UTC, Rovak commented
very nice improvements, thanks!