Translation and minor fix
tronprotocol/wallet-web pull request #160
Opened 2018-05-06 12:04 UTC by fbsobreira

Delete duplicate translation keys
Add missing translation for PT-BR
minor fix: replace "==" for "===", prevent warn, no cast required

2018-05-11 17:50 UTC, Rovak commented
please fix the merge conflict

2018-05-14 20:24 UTC, Jacob8765 requested changes
Looks good, just one comment

2018-05-15 01:09 UTC, fbsobreira commented on src/translations/br.js
> +  "not_started_yet": "Ainda não iniciado"
Sorry I missed that.... The merge review was so simple that I did without tests... will not happen again

2018-05-15 01:36 UTC, Jacob8765 approved these changes

2018-05-15 01:37 UTC, Jacob8765 commented on src/translations/br.js
> +  "not_started_yet": "Ainda não iniciado"
No worries. Thanks for fixing ;)

2018-05-15 15:01 UTC, closed without merging